### ISSUE TITLE
`--pull` option results in error when host:port/path/to/image:tag is used

### ISSUE THREAD

**Issue by adam-moss** [GoogleContainerTools/container-structure-test#104]
When including the `--pull` option in the `test` command a failure is encountered if the host is running the docker registery on a different port (in this use case GitLab, which exposes the registry on port 8443 by default).

The error presented is: API error (400): {"message":"invalid tag format"}

I believe this is being caused by https://github.com/GoogleCloudPlatform/container-structure-test/blob/c6a7fafe63565669bf924e8c70b9a9dfef0130c8/cmd/test.go#L164, which is simply splitting on `:` and has an inherent assumption there is only one present.

**Comment by nkubala** [comment]
Hey @adam-moss, thanks for filing. This isn't something we support currently, but we should fix this up.

**Comment by dlorenc** [comment]
I think this should be fixed now that we switched to the github.com/google/go-containerregistry library. Can you reopen if it's still reproducing?
