### ISSUE TITLE
README file installation and example does not work against latest version

### ISSUE THREAD

**Issue by sedan07** [GoogleContainerTools/container-structure-test#118]
The installation section points users to download the latest binary from: https://storage.googleapis.com/container-structure-test/latest/container-structure-test but this is not the same binary as the github releases page: https://github.com/GoogleContainerTools/container-structure-test/releases, the "Latest release" according the Github is: https://storage.googleapis.com/container-structure-test/v1.1.0/container-structure-test The two downloads are very different in file size.

sha1sums for ref:

```
d3b7828a108f7f12ab9eeea7b1e5b1c6b84615da  latest
435fb13d6ef4f3ee6a7aae5f2f7b47b658c1a7db  v1.1.0
```

I would expect `/latest` to point to the most recent release/tag which is v1.1.0

The "Example Run" example does not work against v1.1.0 as the API appears to have changed considerably. This is even the case when reading the `README.md` file from the `v1.1.0` tag.

Is this repository a stale mirror of another one or are the docs out of date?

**Comment by dlorenc** [comment]
cc @nkubala did you do a release here and only do half of it?

**Comment by nkubala** [comment]
@sedan Thanks for the heads up, and sorry about this. We had an issue with the release automation that was causing the `latest` binary to not be updated on build. I updated the GCS bucket manually, and all subsequent releases should be fixed through https://github.com/GoogleContainerTools/container-structure-test/pull/113.
