### ISSUE TITLE
Error typo: `entrypoint` should be `command`

### ISSUE THREAD

**Issue by paparaka** [GoogleContainerTools/container-structure-test#122]
https://github.com/GoogleContainerTools/container-structure-test/blob/fe1c61b8f02743b43c43843c84c6e0f023526c65/pkg/types/v2/command.go#L46

I have been bashing my head for an hour trying different combinations for `setup`, 
when in fact the problem was with `command`

**Comment by tejal29** [comment]
We will fix the typo here.

**Comment by tejal29** [comment]
https://github.com/GoogleContainerTools/container-structure-test/pull/134
