### ISSUE TITLE
Version in release binary is not correct

### ISSUE THREAD

**Issue by zemanlx** [GoogleContainerTools/container-structure-test#127]
## What is wrong 

Version in release binary is set to `v0.0.0-unset`. It is like this at least for `v1.1.0` and `v1.0.0`

## Steps to reproduce

```bash
curl -LO https://storage.googleapis.com/container-structure-test/v1.1.0/container-structure-test \
&& chmod +x container-structure-test \
&& ./container-structure-test version \
&& rm ./container-structure-test

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9543k  100 9543k    0     0  10.2M      0 --:--:-- --:--:-- --:--:-- 10.2M
v0.0.0-unset
```

If I build it by myself it is ok

```bash
docker run --rm zemanlx/container-structure-test:v1.1.0-alpine version
v1.1.0
```

so it is probably something in your build process.

**Comment by nkubala** [comment]
Ah, you're definitely right. We set the version through the Makefile, so since we started building with Bazel this isn't getting set. I'll go back and update the previous releases.
