### ISSUE TITLE
Useless error when invalid command/flag is passed

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/container-structure-test#135]
On the latest release (v1.2.0), passing an invalid command or flag results in the following error:

```
ERRO[0000] runtime error: invalid memory address or nil pointer dereference
```

This should instead tell the user an invalid command or flag was passed.

**Comment by tejal29** [comment]
Can you paste command here.

**Comment by nkubala** [comment]
Passing anything invalid makes this error happen. `container-structure-test foo` should do it. Seeing it a lot from people using older versions of the args, e.g. `container-structure-test -test.v ...`

**Comment by andmos** [comment]
@nkubala haha I got this now, upgrading from `0.2.1` to `1.2.2`. Took me a while to figure out the new flags. Maybe I'm blind, but I can't seem to find an overview of all available flags in the repo?

**Comment by tejal29** [comment]
@andmos Sorry for the trouble. @nkubala did you get around updating ctc_lib in C-s-t?
If not, i can do it this week and get a release out.

**Comment by nkubala** [comment]
@tejal29 no I didn't get around to updating it, we should do that and get a release out ASAP. Let me know if you need help with it

**Comment by tejal29** [comment]
Spent most of today updating to new CTC.
After going through some update errors, i had to pull the latest container-diff. For that we need to make changes to switch c-s-t to use go-container registry. 
This will take more efforts than i anticipated.

**Comment by xingao267** [comment]
I'm experiencing the same issue while update rules_docker to use the latest version of container-structure-test: https://github.com/bazelbuild/rules_docker/pull/416. @nkubala could you help me take a look at that PR and make sure the command I use to call container-structure-test there has the right and up-to-date flag?
