### ISSUE TITLE
Time duration for each test

### ISSUE THREAD

**Issue by Jeoffreybauvin** [GoogleContainerTools/container-structure-test#139]
It would be nice to have the each time duration (in seconds ?)  for each test, and of course having it in the json report :).

**Comment by nkubala** [comment]
Agreed, this is something we lost when I switched off of the go testing framework. Shouldn't be all that difficult to just wrap each call to `Run()` in a timer and throw that in the report

**Comment by charlyx** [comment]
I'm willing to work on it and open a PR 😄
