### ISSUE TITLE
Tag 1.5.0 is without "v"

### ISSUE THREAD

**Issue by zemanlx** [GoogleContainerTools/container-structure-test#170]
Just noticed that new release `1.5.0` is not tagged as `v1.5.0`. Is that mistake or new thing from this release forward?

![image](https://user-images.githubusercontent.com/18702153/44137381-29edfb5e-a068-11e8-9a4f-3d8367fd393e.png)

**Comment by nkubala** [comment]
@zemanlx thanks for pointing this out, this was my fault. I created the `v1.5.0` tag and updated the release.
