### ISSUE TITLE
Provide Docker image including shell

### ISSUE THREAD

**Issue by OliverNocon** [GoogleContainerTools/container-structure-test#204]
Hi,

Some usage scenarios require a shell to be available in the image:
* debugging
* usage in Jenkins pipelines
* ...

It would be great if there was another Docker image available containing also a shell.
This would be similar to the debug image of the Kaniko project.

As a workaround we created a custom image but would be happy to get rid of it:
https://github.com/SAP/devops-docker-images/tree/master/container-structure-test

Usage inside a Jenkins library (suitable for Docker Deamon as well as Kubernetes cases) as for example here: 
https://github.com/SAP/jenkins-library/blob/master/vars/containerExecuteStructureTests.groovy

What do you think?
Oliver

**Comment by nkubala** [comment]
@OliverNocon thanks for the issue, I would be open to releasing a `container-structure-test-debug` image with a shell and a few debug tools baked into it. would you be interested in writing a short Dockerfile and sending a PR?

**Comment by OliverNocon** [comment]
Yes, I will have a look at it ...
