### ISSUE TITLE
Ability to disable color in output

### ISSUE THREAD

**Issue by derekargueta** [GoogleContainerTools/container-structure-test#205]
When running in Jenkins it yields the escaped characters. Would be great if the color output could be opt-out. I'd be willing to contribute the PR if it's something deemed reasonable.

**Comment by nkubala** [comment]
@derekargueta seems reasonable, PRs definitely welcome! check out the way we [handle color](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/color/formatter.go) in skaffold for some prior art.

**Comment by eunomie** [comment]
PR #208 allows to disable colors, automatically if not in a terminal and manually through a `--no-color` flag

**Comment by eunomie** [comment]
As #208 has been merged, maybe we can close this issue?
