### ISSUE TITLE
Enhance Documentation with best practices

### ISSUE THREAD

**Issue by djuelg** [GoogleContainerTools/container-structure-test#215]
Hi,

I really enjoyed working with your framework. But I encountered pitfalls that consumed some hours. I wrote a blog post about my problems. Maybe you can find something worthy to add to your documentation :)

https://craftcodecrew.com/sophisticated-google-container-structure-tests/

Have a nice day,
Domi

**Comment by bharathguvvala** [comment]
Found this very useful. This variant of syntax for the command tests wasn't mentioned in any of the official documentation. Thanks :)

**Comment by donmccasland** [comment]
Thank you for filing this!  Would you like to submit a PR for the changes?

**Comment by djuelg** [comment]
Yeah, in the next couple of days I can do that :)

**Comment by djuelg** [comment]
Here we go: https://github.com/GoogleContainerTools/container-structure-test/pull/228

It's not much but maybe it helps someone out there
