### ISSUE TITLE
Can this tool run on Windows?

### ISSUE THREAD

**Issue by tqa236** [GoogleContainerTools/container-structure-test#222]
As the title indicates, I would like to know if this tool supports Windows or is there any plan to support Windows in the future? If yes, is there an example somewhere about how to install and run it on Windows?

Thank you very much.

**Comment by sparky005** [comment]
I'd also like to know :) it looks like it's written in go so I think it should be possible? But I don't really know

**Comment by nkubala** [comment]
in theory there isn't anything stopping it from being possible, but the release infrastructure we have isn't set up to build a Windows binary so we'd have to rework the release pipeline. we also don't have any Windows tests so we can't guarantee that everything will work perfectly, but if you'd like to compile from source and try it out for yourself let us know how it goes!

**Comment by sparky005** [comment]
all good @nkubala  :)
so far it seems to work just fine. though as a note for fileExistenceTests, using backslashes (`\`) always fails. You have to use forward slashes (`/`). Mildly confusing for a Windows admin but hardly a show stopper.

**Comment by casz** [comment]
ended up creating docker image for windows (and ubuntu) https://github.com/3shapeAS/containerized-structure-test
https://hub.docker.com/r/3shape/containerized-structure-test

**Comment by lemeurherve** [comment]
Since [v1.10.0](https://github.com/GoogleContainerTools/container-structure-test/releases/tag/v1.10.0) Windows binary are distributed as well.

Now, as most tests contain specific architecture paths, I'm currently adding a specific Windows version of cst configuration file as a workaround.
Is there a better solution by any chance?
