### ISSUE TITLE
Connection refused for curl command in commandtest

### ISSUE THREAD

**Issue by scrumteamravens** [GoogleContainerTools/container-structure-test#223]
I have my DockerFile with below COPY instruction

```
FROM tomcat:9-jre11
ENV CATALINA_HOME=/usr/local/tomcat
ENV PATH=$CATALINA_HOME/bin:$PATH
COPY tests/testentry.sh /usr/local/tomcat/bin
```

Content of testentry.sh
```
#!/bin/bash
catalina.sh run &
sleep 150s
```

commandtest.yaml
```
  - name: "catalina"
    setup: [["/usr/local/tomcat/bin/testentry.sh"]]
    command: "curl"
    args: ["http://localhost:8080"] 
```
Upon execution against the image built, I get the below error in the text execution results -

**0curl: (7) Failed to connect to localhost port 8080: Connection refused
Error: Test 'catalina' exited with incorrect error code. Expected: 0, Actual: 7**

But when I explicitly login into the container using docker exec and perform "curl http://localhost:8080", it works.

**Comment by jacobshirley** [comment]
I'm also running across this now, how did you fix this?
