### ISSUE TITLE
Allow compilation of arm64 and other architectures

### ISSUE THREAD

**Issue by arg2009** [GoogleContainerTools/container-structure-test#256]
I use this tool to test my docker images that I create on my ARM core kubernetes cluster.

In order to compile it I have a small hack to remove the `amd64` architecture hardcoded in the Makefile.
```
sed -i 's/GOARCH = amd64/GOARCH = $(shell go env GOARCH)/g' Makefile
```

I'd like to remove this hardcoded architecture and allow compiling in other architectures.

I have made the modifications on my fork and linked the PR to this issue below.

https://github.com/GoogleContainerTools/container-structure-test/pull/255

**Comment by arg2009** [comment]
#255

**Comment by arg2009** [comment]
Hi @dlorenc and @nkubala ,

I just thought I would tag you on this issue in case you missed it.

I am not sure if PR automatic reviewers tag is enough or if I also need to tag you here so just in case!

Cheers
Ruben

**Comment by arg2009** [comment]
Hi @nkubala ,

Did you see my replies and updates to your comments?

Let me know what you think about my replies.

Cheers
Ruben

**Comment by nkubala** [comment]
closed by https://github.com/GoogleContainerTools/container-structure-test/pull/255
