### ISSUE TITLE
Run in Kubernetes (without daemon)

### ISSUE THREAD

**Issue by cmamigonian** [GoogleContainerTools/container-structure-test#270]
I'm trying to run `container-structure-test` in CI which is running in k8s.  For security reasons I'm not running Docker-in-Docker and mounting the daemon into my pod, so I won't have the daemon available to run the image for the tests.  I don't know if this is possible, but could something be done in this project to enable this use case?

**Comment by nkubala** [comment]
hey @cmamigonian, we have support for a `tar` driver which will flatten the filesystem of your image and run tests against that. it should work fine with no Docker daemon available.

`container-structure-test test --driver tar --image gcr.io/registry/image:latest --config config.yaml`

hope this is what you were looking for!

**Comment by cmamigonian** [comment]
that's great, thank you!
