### ISSUE TITLE
Release 1.13.0 introduced backwards incompatibility with schema version 2.0.0 for metadataTest.env field

### ISSUE THREAD

**Issue by mmcaya** [GoogleContainerTools/container-structure-test#322]
### Expected behavior
- Upgrading from version `1.11.0` to `1.13.0` should remain backwards compatible with any container structure test configuration marked `schemaVersion: 2.0.0` (Either supporting _both_ the old and new field names, or not allowing such field name changes to occur under minor revision releases)  

Alternate solutions: 
- Any breaking changes to the schema should require a major version change to the schema.
- Explicit schema versioning policies should be documented and enforced in a similar manner to other projects that explicitly use `container-structure-test` (e.g. [skaffold](https://skaffold.dev/docs/pipeline-stages/testers/structure/) )
- Explicit marking of backwards compatibility breaks in the CHANGELOG.md
- Upgrade guides and/or tooling to automatically fix schema changes (similar to `skaffold fix`) would also be desirable.

### Actual behavior

The `metadataTest.env` field name is no longer valid as part of `schemaVersion: 2.0.0`

Example:
```
Error: error parsing config file: error unmarshalling config: yaml: unmarshal errors:
  line 3: field env not found in type v2.MetadataTest
```

`metadataTest.env` was renamed `metadataTest.envVars` via the following PR:

https://github.com/GoogleContainerTools/container-structure-test/pull/314
https://github.com/GoogleContainerTools/container-structure-test/pull/315

Upgrading from `1.11.0` to `1.13.0` now requires explicit update to any configuration files, and would potentially break any automation dependent on those configuration files.

### Information

- container-structure-test version: v1.13.0
- Operating system: macOS 12.5.1
- Installed via: curl

### Steps to reproduce the behavior

Minimal configuration:

- Contents of structure-test.yml:

```yaml
schemaVersion: 2.0.0
metadataTest:
  env:
    - key: GOPATH
      value: /go
```

GOOD - v1.11.0
> 
```
container-structure-test test --image golang:1.19-alpine --config structure-test.yml

===========================================
====== Test file: structure-test.yml ======
===========================================
=== RUN: Metadata Test
--- PASS
duration: 0s

===========================================
================= RESULTS =================
===========================================
Passes:      1
Failures:    0
Duration:    0s
Total tests: 1

PASS

```

ERROR - v1.13.0
```
> container-structure-test test --image golang:1.19-alpine --config structure-test.yml

===========================================
====== Test file: structure-test.yml ======
===========================================
=== RUN: 
--- FAIL
duration: 0s
Error: error parsing config file: error unmarshalling config: yaml: unmarshal errors:
  line 3: field env not found in type v2.MetadataTest

===========================================
================= RESULTS =================
===========================================
Passes:      0
Failures:    1
Duration:    0s
Total tests: 1

FAIL
FATA[0000] FAIL      
```

**Comment by mmcaya** [comment]
Related relevant comment from original PR: https://github.com/GoogleContainerTools/container-structure-test/pull/314#issuecomment-1306192841

**Comment by coopernetes** [comment]
I would like to see the schema respected so opened #324

**Comment by coopernetes** [comment]
I'm interested in helping to resolve this. Does #325 solve for this immediate break? If that PR is accepted, the next release will re-introduce compatibility between both `env` and `envVars` fields. 

It's also probably worth adding some additional tests to validate future changes don't break the API without a schema version increase.

**Comment by loosebazooka** [comment]
I think we just need to move on here unfortunately. There isn't much manpower behind this project right now. So we're triyng to keep it as simple as possible. Hopefully everyone has updated their builds.
