### ISSUE TITLE
Add platform parameter to support testing multi-platform images

### ISSUE THREAD

**Issue by michalszelagsonos** [GoogleContainerTools/container-structure-test#373]
Docker supports building an image for multiple platforms, amd64 and arm64 for example, and it even supports running containers using platform emulators, if they are installed.  I have a project where I am building an image for both amd64 and arm64.  I build both platforms on amd64 compute and publish a single image using multi-platform manifest.  This is supported with buildx.  Since there are some significant differences how the image is built for each platform, I would like to be able to test each platform to make sure they both function the same way.  The only way I think I can do that right now is to run the tests for each platform on their respective architecture, which is not very practical.  For example, if I want to test amd64, I need to run tests on amd64 compute.  If I want to verify arm64, I need to run on arm64.  If I could specify the platform to be used for container execution, that would solve this issue.  Assumption is that I need to have a functioning docker environment that allows me to run an emulated environment.  So, for example, if I can do this in my amd64 environment:
```shell
docker run --platform linux/arm64 foo
```
Then it would be awesome to be able to do this:
```shell
container-structure-test test --platform linux/arm64 --image foo
```
The CLI option is very appealing since I would be able to reuse the same test config for all of the platforms I am building for.

**Comment by Sineaggi** [comment]
From what I can tell, the platform flag is not exposed to the bazel rule. Fixed in https://github.com/GoogleContainerTools/container-structure-test/pull/469
