### ISSUE TITLE
New Testcontainers driver

### ISSUE THREAD

**Issue by alexeagle** [GoogleContainerTools/container-structure-test#381]
Currently the available drivers either require a docker daemon running on the current machine, or have no container runtime at all.

TestContainers Cloud https://testcontainers.com/cloud/ is a nice way to get remote containers instead.
You can think of it a bit like RBE, but MUCH easier to scale out workloads.

I think it's pretty trivial for someone comfortable in Go to take the https://github.com/testcontainers/testcontainers-go library and make another file in the drivers/ folder here and wire it up.

**Comment by alexeagle** [comment]
@loosebazooka would you be okay approving such a contribution?

**Comment by loosebazooka** [comment]
yeah

**Comment by alexeagle** [comment]
@thesayyn determined that this seems to be unneeded.

After setting up TestContainers Cloud, the client-side agent has created a `~/.testcontainers.properties` file (e.g. by running https://github.com/AtomicJar/testcontainers-cloud-setup-action)
This file contains a `tc.host` property we can use to set `DOCKER_HOST` in the environment, and then the standard `docker` driver in this repo will work to use the remote container runtime.
