### ISSUE TITLE
stderr output instead of stdout for cmd test

### ISSUE THREAD

**Issue by goffinf** [GoogleContainerTools/container-structure-test#52]
I have an image that I am testing which includes the AWS CLI binary. I want to test that the version is what I expect. I have this command ...

```
    # check the aws-cli binary is the correct version
  - name: "aws-cli"
    command: "aws"
    args: ["--version"]
    expectedOutput: ["1.14.17"]
```
This test fails ... (some output elided for brevity)

```
Using driver docker
=== RUN   TestAll
2018/01/29 23:41:31 Running tests for file cmd_tests.yaml
...
=== RUN   TestAll/Command_Test:_aws-cli
--- FAIL: TestAll (1.96s)
...
    --- FAIL: TestAll/Command_Test:_aws-cli (1.07s)
        docker_driver.go:88: stderr: aws-cli/1.14.17 Python/2.7.13 Linux/3.10.0-514.26.2.el7.x86_64 botocore/1.8.21
        utils.go:33: Expected string '1.14.17' not found in output!
FAIL
```
As we can see the AWS cli version string *was* output, but it was sent to stderr rather than stdout ?
If I exec into this container and run aws --version it returns the expected string as above to the console. 

Of course I could get a PASS for the test by changing expectedOutput to expectedError but I'm curious why this has happened (there are other similar tests I use inside the same image and they all return successfully thru stdout).

Any ideas ?

Regards

Fraser.

**Comment by nkubala** [comment]
Hmm, just by looking at this it seems that there are two things going on.

The first is that the output of your command is going to stderr, but the streams are definitely kept separate when attaching to the docker logs (see [here](https://github.com/GoogleCloudPlatform/container-structure-test/blob/master/drivers/docker_driver.go#L323)), so I think this might actually a weird thing with the command you're running. Can you try running it directly in your container again and redirecting stderr to a file (`command 2> stderr.txt`) and see if it's printing to the wrong (or at least unexpected) stream?

The second thing is that you're using a simple matching string for the expectedOutput here, but these are actually interpreted by the testing framework as regexes. This means that to actually match the string `"1.14.17"`, you'll need to use something like ```expectedOutput: [".*1\.14\.17.*"]``` if you expect there to be surrounding output. I know this is a bit of a weird UX, and something I'd like to improve.

**Comment by Evesy** [comment]
@goffinf What version of python do you have installed?

If you're using a python version <3.4 then `aws --version` will print to stderr, however more recent versions should print to stdout.

**Comment by donmccasland** [comment]
I don't think we need to alter the logic for the test infrastructure.  I think there are 3 suitable workarounds for the fact that aws --version behaves in an unexpected way.  

I'm going to close "won't fix," but if you disagree please reopen with discussion.
