### ISSUE TITLE
File existence tests `shouldExist` defaults to False

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/container-structure-test#56]
If this field isn't specified in the config, it default to `False`, which is counterintuitive.

The issue here is that we can't set default values on the struct in go, but when the fields get unmarshaled into the struct go chooses `False` as the default. We could init the holder struct with default values first, and then unmarshal, but the problem with that is that we don't know how many defaulted structs to put in each place (e.g. if we init with two `FileExistenceTest` structs, and the config specifies three, the third one doesn't get the default values). We might need to override the unmarshalling method to use an explicit constructor for each struct here.

**Comment by Danielle33** [comment]
Okay
