### ISSUE TITLE
File Content Tests should allow to check owner and group

### ISSUE THREAD

**Issue by dzavalkinolx** [GoogleContainerTools/container-structure-test#81]
I'm building a base docker image with nginx which should run all processes as nginx users (to be able to use this docker in openshift). I need to verify that certain directories/files are owned by nginx user to allow child images put files there.

**Comment by nkubala** [comment]
Ah ok I see, this wouldn't be covered in the permissions bits for the file since it's user and group info. This should be doable.

**Comment by amitsaha** [comment]
Isn't this already supported as per the docs (via `Uid` and `Gid` fields?) https://github.com/GoogleContainerTools/container-structure-test#file-existence-tests

**Comment by donmccasland** [comment]
Yeah, file-existence uid/guid should cover this.
